#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : renderproto
Version  : 0.11.1
Release  : 7
URL      : http://xorg.freedesktop.org/releases/individual/proto/renderproto-0.11.1.tar.bz2
Source0  : http://xorg.freedesktop.org/releases/individual/proto/renderproto-0.11.1.tar.bz2
Summary  : Render extension headers
Group    : Development/Tools
License  : HPND
Requires: renderproto-doc
BuildRequires : pkgconfig(xorg-macros)

%description
X Rendering Extension
This extension defines the protcol for a digital image composition as
the foundation of a new rendering model within the X Window System.

%package dev
Summary: dev components for the renderproto package.
Group: Development
Provides: renderproto-devel

%description dev
dev components for the renderproto package.


%package doc
Summary: doc components for the renderproto package.
Group: Documentation

%description doc
doc components for the renderproto package.


%prep
%setup -q -n renderproto-0.11.1

%build
export LANG=C
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/extensions/render.h
/usr/include/X11/extensions/renderproto.h
/usr/lib64/pkgconfig/renderproto.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/renderproto/*
